previewsEnabled: true
services:
  - type: web
    name: Sophies Demo API
    env: node
    plan: free
    region: singapore
    repo: https://github.com/psse-cpu/sophies-demo-2022.git
    buildCommand: pnpm be deploy
    startCommand: pnpm be start:prod
    pullRequestPreviewsEnabled: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sophies_pg_prod
          property: connectionString
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: GOOGLE_OAUTH_REDIRECT_URL
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1w
      - key: JWT_SECRET
        sync: false
    autoDeploy: false # optional

  - type: web
    name: Sophies Demo API Staging
    env: node
    plan: free
    region: singapore
    repo: https://github.com/psse-cpu/sophies-demo-2022.git
    buildCommand: pnpm be deploy
    startCommand: pnpm be start:prod
    pullRequestPreviewsEnabled: false
    envVars:
      - key: STAGING
        value: 1
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: GOOGLE_OAUTH_REDIRECT_URL
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1w
      - key: JWT_SECRET
        sync: false
    autoDeploy: true # optional

  # A static site
  - type: web
    name: Sophies Demo
    env: static
    buildCommand: pnpm fe deploy
    staticPublishPath: ./frontend/dist/spa
    pullRequestPreviewsEnabled: false # optional
    autoDeploy: false

  - type: web
    name: Sophies Demo Staging
    env: static
    buildCommand: pnpm fe deploy
    staticPublishPath: ./frontend/dist/spa
    pullRequestPreviewsEnabled: false # optional
    autoDeploy: true

databases:
  - name: sophies_pg_prod
    region: singapore
    plan: free
    postgresMajorVersion: 14
    databaseName: sophies_demo # optional (Render may add a suffix)
    user: mykvanfifi
